-- Yhden baarin asennus: bar_name-sarakkeet ja baarin tunniste (pubs.slug) poistetaan. Jäljelle jää yksi baari (pubs-rivi) ja yksi julkinen profiili.
DELETE FROM `pub_profiles` WHERE `bar_name` <> COALESCE((SELECT `slug` FROM `pubs` ORDER BY `id` LIMIT 1), '');
ALTER TABLE `pub_profiles` ADD COLUMN `id` tinyint(4) NOT NULL DEFAULT 1 FIRST, DROP PRIMARY KEY, ADD PRIMARY KEY (`id`), DROP COLUMN `bar_name`;
ALTER TABLE `audit_log` DROP INDEX `pub_time`, ADD INDEX `idx_created` (`created_at`), DROP COLUMN `bar_name`;
ALTER TABLE `availability` DROP COLUMN `bar_name`;
ALTER TABLE `availability_rules` DROP COLUMN `bar_name`;
ALTER TABLE `bookings` DROP INDEX `pub_time`, ADD INDEX `idx_starts` (`starts_at`), DROP COLUMN `bar_name`;
ALTER TABLE `cash_reports` DROP INDEX `pub_date`, ADD UNIQUE INDEX `uq_date` (`date`), DROP COLUMN `bar_name`;
ALTER TABLE `checklists` DROP COLUMN `bar_name`;
ALTER TABLE `daily_sales` DROP PRIMARY KEY, ADD PRIMARY KEY (`date`), DROP COLUMN `bar_name`;
ALTER TABLE `documents` DROP COLUMN `bar_name`;
ALTER TABLE `events` DROP INDEX `pub_date`, ADD INDEX `idx_date` (`date`), DROP COLUMN `bar_name`;
ALTER TABLE `guests` DROP INDEX `pub_email`, ADD UNIQUE INDEX `uq_email` (`email`), DROP COLUMN `bar_name`;
ALTER TABLE `hour_confirmations` DROP INDEX `pub_month`, ADD INDEX `idx_month` (`month`), DROP COLUMN `bar_name`;
ALTER TABLE `kudos` DROP INDEX `pub_created`, ADD INDEX `idx_created` (`created_at`), DROP COLUMN `bar_name`;
ALTER TABLE `notices` DROP COLUMN `bar_name`;
ALTER TABLE `private_messages` DROP COLUMN `bar_name`;
ALTER TABLE `shifts` DROP INDEX `pub_date`, ADD INDEX `idx_date` (`date`), DROP COLUMN `bar_name`;
ALTER TABLE `shift_logs` DROP INDEX `pub_created`, ADD INDEX `idx_created` (`created_at`), DROP COLUMN `bar_name`;
ALTER TABLE `shift_templates` DROP COLUMN `bar_name`;
ALTER TABLE `shopping_list` DROP INDEX `pub_status`, ADD INDEX `idx_status` (`status`), DROP COLUMN `bar_name`;
ALTER TABLE `skills` DROP COLUMN `bar_name`;
ALTER TABLE `sms_log` DROP INDEX `pub_month`, ADD INDEX `idx_created` (`created_at`), DROP COLUMN `bar_name`;
ALTER TABLE `staffing_rules` DROP COLUMN `bar_name`;
ALTER TABLE `surveys` DROP COLUMN `bar_name`;
ALTER TABLE `tasks` DROP COLUMN `bar_name`;
ALTER TABLE `task_completions` DROP INDEX `pub_date_task`, ADD UNIQUE INDEX `uq_date_task` (`date`, `task_id`), DROP COLUMN `bar_name`;
ALTER TABLE `time_entries` DROP INDEX `pub_clock`, ADD INDEX `idx_clock` (`clock_in`), DROP COLUMN `bar_name`;
ALTER TABLE `users` DROP INDEX `unique_user_per_pub`, ADD UNIQUE INDEX `uq_username` (`username`), DROP COLUMN `bar_name`;
ALTER TABLE `week_templates` DROP COLUMN `bar_name`;
ALTER TABLE `pubs` DROP COLUMN `slug`;
